import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Welcome to my HTML/CSS certification projects</a>
        </h1>



        <div className={styles.grid}>


        <Link href="/projects/Tributepage" passHref className={styles.card}>
        <div className={styles.card}>
            <h2>Tribute Page &rarr;</h2>
           <img></img>
          </div>  
          </Link>
      
 

          <Link href="/projects/Tributepage" passHref className={styles.card}>
        <div className={styles.card}>
            <h2>Survey Form &rarr;</h2>
           <img></img>
          </div>  
          </Link>
  

          <Link href="/projects/Tributepage" passHref className={styles.card}>
        <div className={styles.card}>
            <h2>Product Landing Page &rarr;</h2>
           <img></img>
          </div>   
          </Link>

     

          <Link href="/projects/Tributepage" passHref className={styles.card}>
        <div className={styles.card}>
            <h2>Technical Documentation Page &rarr;</h2>
           <img></img>
          </div>      
          </Link>   

          <Link href="/projects/Tributepage" passHref className={styles.card}>
        <div className={styles.card}>
            <h2>Webpage example&rarr;</h2>
           <img></img>
          </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Source Code{' '}
          <span className={styles.logo}>
            
          </span>
        </a>
      </footer>
    </div>
  )
}
